# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Deploy Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq libsnappy-dev
    - name: Install protoc
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip
        unzip protoc-28.3-linux-x86_64.zip -d protoc
        echo "$PWD/protoc/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        uv pip install --system -e ".[dev]"
        uv pip install --system build twine rich
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        # Build the gencode:
        PYTHONPATH=$PYTHONPATH:$(pwd) python3 dumper/run.py
        # Build the package:
        python -m build
        # Upload the package:
        twine upload dist/*
